In [1]:
import pandas as pd

vendas = {
    'data': ['15/02/2021', '16/02/2021'],
    'valor': [100, 200],
    'produto': ['camiseta', 'camiseta'],
    'quantidade': [2, 3],
}

vendas_df = pd.DataFrame(vendas)

display(vendas_df)

         data  valor   produto  quantidade
0  15/02/2021    100  camiseta           2
1  16/02/2021    200  camiseta           3

In [2]:
vendas_df = pd.read_excel("Vendas.xlsx")
display(vendas_df)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71
...,...,...,...,...,...,...,...
93905,65012,2019-11-30,Shopping Vila Velha,Mochila Xadrez,2,283,566
93906,65013,2019-11-30,Ribeirão Shopping,Pulseira Listrado,2,79,158
93907,65013,2019-11-30,Ribeirão Shopping,Cueca Listrado,3,67,201
93908,65014,2019-11-30,Shopping Morumbi,Pulseira Linho,5,114,570
93909,65014,2019-11-30,Shopping Morumbi,Casaco Xadrez,4,259,1036

In [3]:
#.head -> mostra apenas a cabeça do arquivo
display(vendas_df.head)

<bound method NDFrame.head of        Código Venda       Data              ID Loja            Produto  \
0                 1 2019-01-01   Iguatemi Esplanada     Sapato Estampa
1                 1 2019-01-01   Iguatemi Esplanada           Camiseta
2                 1 2019-01-01   Iguatemi Esplanada      Sapato Xadrez
3                 2 2019-01-02       Norte Shopping            Relógio
4                 2 2019-01-02       Norte Shopping       Chinelo Liso
...             ...        ...                  ...                ...
93905         65012 2019-11-30  Shopping Vila Velha     Mochila Xadrez
93906         65013 2019-11-30    Ribeirão Shopping  Pulseira Listrado
93907         65013 2019-11-30    Ribeirão Shopping     Cueca Listrado
93908         65014 2019-11-30     Shopping Morumbi     Pulseira Linho
93909         65014 2019-11-30     Shopping Morumbi      Casaco Xadrez

       Quantidade  Valor Unitário  Valor Final
0               1             358          358
1               2             180          360
2               1             368          368
3               3             200          600
4               1              71           71
...           ...             ...          ...
93905           2             283          566
93906           2              79          158
93907           3              67          201
93908           5             114          570
93909           4             259         1036

[93910 rows x 7 columns]>

In [4]:
#.head(x) -. x mostra a quantidade de linhas que quer visualizar do arquivo
display(vendas_df.head(10))

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71
5,3,2019-01-02,Rio Mar Shopping Fortaleza,Cinto Linho,1,248,248
6,5,2019-01-02,Shopping Barra,Calça,1,170,170
7,6,2019-01-02,Shopping Ibirapuera,Polo Listrado,4,149,596
8,7,2019-01-02,Norte Shopping,Camisa Gola V Listrado,1,116,116
9,7,2019-01-02,Norte Shopping,Camisa Liso,1,105,105

In [5]:
#.shape -> mostra a quantidade de linhas e de colunas 
display(vendas_df.shape)

(93910, 7)

In [7]:
#.describe() -> calcula a média, da o desvio padrão, da o minímo, o máximo, um quartio. Visão geral das informações
display(vendas_df.describe())

       Código Venda    Quantidade  Valor Unitário   Valor Final
count  93910.000000  93910.000000    93910.000000  93910.000000
mean   32464.762155      2.166553      191.725886    414.862656
std    18809.007093      1.258732      145.215519    434.846228
min        1.000000      1.000000       30.000000     30.000000
25%    16204.000000      1.000000      100.000000    156.000000
50%    32367.000000      2.000000      155.000000    274.000000
75%    48793.750000      3.000000      248.000000    524.000000
max    65014.000000      5.000000      750.000000   3750.000000

In [8]:
#Pegar 1 Coluna -> Apenas criar uma variável e passar como paramêtro o nome da coluna.
produto = vendas_df['Produto']
display(produto)

0           Sapato Estampa
1                 Camiseta
2            Sapato Xadrez
3                  Relógio
4             Chinelo Liso
               ...
93905       Mochila Xadrez
93906    Pulseira Listrado
93907       Cueca Listrado
93908       Pulseira Linho
93909        Casaco Xadrez
Name: Produto, Length: 93910, dtype: object

In [11]:
#Pegar 2 Colunas -> mesmo método que pegar 1 coluna, apenas adicionar o nome da coluna que quer pegar, apenas adicionar a mais []
produtos = vendas_df[['Produto', 'ID Loja']]
display(produtos)

                 Produto              ID Loja
0         Sapato Estampa   Iguatemi Esplanada
1               Camiseta   Iguatemi Esplanada
2          Sapato Xadrez   Iguatemi Esplanada
3                Relógio       Norte Shopping
4           Chinelo Liso       Norte Shopping
...                  ...                  ...
93905     Mochila Xadrez  Shopping Vila Velha
93906  Pulseira Listrado    Ribeirão Shopping
93907     Cueca Listrado    Ribeirão Shopping
93908     Pulseira Linho     Shopping Morumbi
93909      Casaco Xadrez     Shopping Morumbi

[93910 rows x 2 columns]

In [12]:
#.loc -> pegar uma linha, ele localiza as linhas pelos seus IDS 
display(vendas_df.loc[1])

Código Venda                        1
Data              2019-01-01 00:00:00
ID Loja            Iguatemi Esplanada
Produto                      Camiseta
Quantidade                          2
Valor Unitário                    180
Valor Final                       360
Name: 1, dtype: object

In [13]:
#.loc -> pegar uma sequência de linhas, ele localiza as linhas pelos seus IDS 
display(vendas_df.loc[1:5])

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71
5,3,2019-01-02,Rio Mar Shopping Fortaleza,Cinto Linho,1,248,248

In [15]:
#.loc -> pegar linhas que correspondem a uma condição, passar dentro do loc
#coluna_loja -> nome_loja
#vendas_df['ID Loja'] == 'Norte Shopping'
vendas_norteshopping_df = vendas_df.loc[vendas_df['ID Loja'] == 'Norte Shopping']
display(vendas_norteshopping_df)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71
8,7,2019-01-02,Norte Shopping,Camisa Gola V Listrado,1,116,116
9,7,2019-01-02,Norte Shopping,Camisa Liso,1,105,105
100,73,2019-01-02,Norte Shopping,Cueca Xadrez,5,60,300
...,...,...,...,...,...,...,...
93716,64888,2019-11-30,Norte Shopping,Polo Xadrez,1,142,142
93754,64914,2019-11-30,Norte Shopping,Calça Liso,1,190,190
93755,64914,2019-11-30,Norte Shopping,Casaco Estampa,2,256,512
93756,64914,2019-11-30,Norte Shopping,Gorro,2,80,160
93852,64980,2019-11-30,Norte Shopping,Bermuda Linho,1,195,195

In [17]:
#pegar várias linhas e colunas usando o loc
#vendas_norteshopping_df = vendas_df.loc[linhas, colunas]
vendas_norteshopping_df = vendas_df.loc[vendas_df['ID Loja'] == 'Norte Shopping', ['ID Loja', 'Produto', 'Quantidade']]
display(vendas_norteshopping_df)

              ID Loja                 Produto  Quantidade
3      Norte Shopping                 Relógio           3
4      Norte Shopping            Chinelo Liso           1
8      Norte Shopping  Camisa Gola V Listrado           1
9      Norte Shopping             Camisa Liso           1
100    Norte Shopping            Cueca Xadrez           5
...               ...                     ...         ...
93716  Norte Shopping             Polo Xadrez           1
93754  Norte Shopping              Calça Liso           1
93755  Norte Shopping          Casaco Estampa           2
93756  Norte Shopping                   Gorro           2
93852  Norte Shopping           Bermuda Linho           1

[3924 rows x 3 columns]

In [18]:
#.loc -> Pegar um valor específico  
#display(vendas_df.loc[linha, coluna])
display(vendas_df.loc[1, 'Produto'])

'Camiseta'

In [19]:
#ADICIONAR 1 COLUNA
#A partir de uma coluna 
vendas_df['Comissão'] = vendas_df['Valor Final'] * 0.05
display(vendas_df)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Comissão
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358,17.90
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360,18.00
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368,18.40
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600,30.00
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71,3.55
...,...,...,...,...,...,...,...,...
93905,65012,2019-11-30,Shopping Vila Velha,Mochila Xadrez,2,283,566,28.30
93906,65013,2019-11-30,Ribeirão Shopping,Pulseira Listrado,2,79,158,7.90
93907,65013,2019-11-30,Ribeirão Shopping,Cueca Listrado,3,67,201,10.05
93908,65014,2019-11-30,Shopping Morumbi,Pulseira Linho,5,114,570,28.50
93909,65014,2019-11-30,Shopping Morumbi,Casaco Xadrez,4,259,1036,51.80

In [20]:
#ADICIONAR 1 COLUNA
#Criar uma coluna com valor padrão
#vendas_df.loc[linha, coluna] = 0
#vendas_df.loc[:, "Imposto"]] = 0
vendas_df.loc[:, "Imposto"] = 0
display(vendas_df)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Comissão,Imposto
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358,17.90,0
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360,18.00,0
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368,18.40,0
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600,30.00,0
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71,3.55,0
...,...,...,...,...,...,...,...,...,...
93905,65012,2019-11-30,Shopping Vila Velha,Mochila Xadrez,2,283,566,28.30,0
93906,65013,2019-11-30,Ribeirão Shopping,Pulseira Listrado,2,79,158,7.90,0
93907,65013,2019-11-30,Ribeirão Shopping,Cueca Listrado,3,67,201,10.05,0
93908,65014,2019-11-30,Shopping Morumbi,Pulseira Linho,5,114,570,28.50,0
93909,65014,2019-11-30,Shopping Morumbi,Casaco Xadrez,4,259,1036,51.80,0

In [21]:
vendas_dez_df = pd.read_excel("Vendas - Dez.xlsx")
display(vendas_dez_df)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65014,2019-12-01,Shopping Morumbi,Sunga Listrado,5,114,570
1,65014,2019-12-01,Shopping Morumbi,Casaco Listrado,1,269,269
2,65016,2019-12-01,Iguatemi Campinas,Sapato Listrado,2,363,726
3,65016,2019-12-01,Iguatemi Campinas,Casaco,1,250,250
4,65017,2019-12-01,Shopping SP Market,Gorro Liso,3,92,276
...,...,...,...,...,...,...,...
7084,69996,2019-12-26,Center Shopping Uberlândia,Short Listrado,2,102,204
7085,69996,2019-12-26,Center Shopping Uberlândia,Mochila,4,270,1080
7086,69996,2019-12-26,Center Shopping Uberlândia,Pulseira Estampa,1,87,87
7087,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108
7088,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266

In [22]:
#ADICIONAAR 1 LINHA 
#Linha de um complemento de base de dados 
vendas_df = vendas_df.append(vendas_dez_df)
display(vendas_df)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Comissão,Imposto
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358,17.90,0.0
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360,18.00,0.0
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368,18.40,0.0
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600,30.00,0.0
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71,3.55,0.0
...,...,...,...,...,...,...,...,...,...
7084,69996,2019-12-26,Center Shopping Uberlândia,Short Listrado,2,102,204,NaN,NaN
7085,69996,2019-12-26,Center Shopping Uberlândia,Mochila,4,270,1080,NaN,NaN
7086,69996,2019-12-26,Center Shopping Uberlândia,Pulseira Estampa,1,87,87,NaN,NaN
7087,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108,NaN,NaN
7088,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266,NaN,NaN

In [23]:
#EXCLUIR LINHAS E COLUNAS 
vendas_df = vendas_df.drop("Imposto", axis=1)
display(vendas_df)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Comissão
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358,17.90
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360,18.00
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368,18.40
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600,30.00
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71,3.55
...,...,...,...,...,...,...,...,...
7084,69996,2019-12-26,Center Shopping Uberlândia,Short Listrado,2,102,204,NaN
7085,69996,2019-12-26,Center Shopping Uberlândia,Mochila,4,270,1080,NaN
7086,69996,2019-12-26,Center Shopping Uberlândia,Pulseira Estampa,1,87,87,NaN
7087,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108,NaN
7088,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266,NaN

In [24]:
 # excluir determinada linha
 #EIXO (AXIS) 0 É LINHA , E EIXO (AXIS) 1 É COLUNA
 vendas_df = vendas_df.drop(0, axis=0)
 display(vendas_df)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Comissão
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360,18.00
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368,18.40
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600,30.00
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71,3.55
5,3,2019-01-02,Rio Mar Shopping Fortaleza,Cinto Linho,1,248,248,12.40
...,...,...,...,...,...,...,...,...
7084,69996,2019-12-26,Center Shopping Uberlândia,Short Listrado,2,102,204,NaN
7085,69996,2019-12-26,Center Shopping Uberlândia,Mochila,4,270,1080,NaN
7086,69996,2019-12-26,Center Shopping Uberlândia,Pulseira Estampa,1,87,87,NaN
7087,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108,NaN
7088,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266,NaN

In [26]:
# Deletar linhas e colunas completamentes vazias
vendas_df = vendas_df.dropna(how = 'all')
display(vendas_df)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Comissão
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360,18.00
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368,18.40
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600,30.00
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71,3.55
5,3,2019-01-02,Rio Mar Shopping Fortaleza,Cinto Linho,1,248,248,12.40
...,...,...,...,...,...,...,...,...
7084,69996,2019-12-26,Center Shopping Uberlândia,Short Listrado,2,102,204,NaN
7085,69996,2019-12-26,Center Shopping Uberlândia,Mochila,4,270,1080,NaN
7086,69996,2019-12-26,Center Shopping Uberlândia,Pulseira Estampa,1,87,87,NaN
7087,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108,NaN
7088,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266,NaN

In [31]:
# Deletar linhas completamentes vazias
vendas_df = vendas_df.dropna(how='all', axis=0)

In [32]:
#Deletar colunas completamente vazias
vendas_df = vendas_df.dropna(how='all', axis=1)

In [35]:
#Preencher os valores vazios com a média da coluna
'''vendas_df['Comissão'] = vendas_df['Comissão'].fillna(vendas_df['Comissão'].mean())
display(vendas_df)'''
#Não foi possível preencher por conta de no código acima eu ter excluído todos os valores vazios

"vendas_df['Comissão'] = vendas_df['Comissão'].fillna(vendas_df['Comissão'].mean())\ndisplay(vendas_df)"

In [37]:
#preencher com o último valor
'''vendas_df.ffill()'''

'vendas_df.ffill()'

In [39]:
#Filtra os dados que pedir do DataFrame
transacoes_loja = vendas_df['ID Loja'].value_counts() 
display(transacoes_loja)

Shopping Vila Velha                 4234
Palladium Shopping Curitiba         4210
Norte Shopping                      4179
Rio Mar Shopping Fortaleza          4118
Bourbon Shopping SP                 4116
Iguatemi Campinas                   4108
Rio Mar Recife                      4099
Shopping Center Leste Aricanduva    4093
Shopping SP Market                  4080
Shopping Ibirapuera                 4051
Novo Shopping Ribeirão Preto        4049
Ribeirão Shopping                   4048
Salvador Shopping                   4030
Shopping Center Interlagos          4021
Shopping Iguatemi Fortaleza         4021
Center Shopping Uberlândia          4013
Shopping Eldorado                   4002
Passei das Águas Shopping           4000
Shopping União de Osasco            3995
Iguatemi Esplanada                  3979
Shopping Barra                      3962
Shopping Morumbi                    3959
Parque Dom Pedro Shopping           3902
Shopping Recife                     3891
Shopping Midway Mall                3837
Name: ID Loja, dtype: int64

In [40]:
#GROUPBY
faturamento_produto = vendas_df.groupby('Produto').sum()
display(faturamento_produto)

                  Código Venda  Quantidade  Valor Unitário  Valor Final
Produto
Bermuda               29736664        1815          124950       272250
Bermuda Estampa       28011111        1726          135538       291694
Bermuda Linho         32794909        2024          179010       394680
Bermuda Liso          28019004        1756          127170       275692
Bermuda Listrado      29304435        1799          138224       293237
...                        ...         ...             ...          ...
Tênis Estampa         29267679        1788          215040       457728
Tênis Linho           29440230        1832          249900       538608
Tênis Liso            30105216        1784          221046       474544
Tênis Listrado        28850195        1836          220604       481032
Tênis Xadrez          29758793        1775          219891       459725

[120 rows x 4 columns]

In [41]:
#GROUPBY
faturamento_produto = vendas_df[['Produto', 'Valor Final']].groupby('Produto').sum()
display(faturamento_produto)

                  Valor Final
Produto
Bermuda                272250
Bermuda Estampa        291694
Bermuda Linho          394680
Bermuda Liso           275692
Bermuda Listrado       293237
...                       ...
Tênis Estampa          457728
Tênis Linho            538608
Tênis Liso             474544
Tênis Listrado         481032
Tênis Xadrez           459725

[120 rows x 1 columns]

In [42]:
#MESCLAR 2 DATAFRAMES
gerentes_df = pd.read_excel("Gerentes.xlsx")

vendas_df = vendas_df.merge(gerentes_df)
display(vendas_df)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Comissão,Gerente
0,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360,18,Salvador
1,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368,18.4,Salvador
2,21,2019-01-02,Iguatemi Esplanada,Camisa Gola V Listrado,2,116,232,11.6,Salvador
3,34,2019-01-02,Iguatemi Esplanada,Sapato Listrado,1,363,363,18.15,Salvador
4,34,2019-01-02,Iguatemi Esplanada,Camisa Gola V Liso,2,118,236,11.8,Salvador
...,...,...,...,...,...,...,...,...,...
100992,69846,2019-12-25,Salvador Shopping,Short Estampa,2,96,192,<bound method Series.mean of 1 18.00\n2 ...,Mateus
100993,69846,2019-12-25,Salvador Shopping,Tênis Estampa,5,256,1280,<bound method Series.mean of 1 18.00\n2 ...,Mateus
100994,69850,2019-12-25,Salvador Shopping,Calça Estampa,4,177,708,<bound method Series.mean of 1 18.00\n2 ...,Mateus
100995,69972,2019-12-26,Salvador Shopping,Terno Liso,3,720,2160,<bound method Series.mean of 1 18.00\n2 ...,Mateus
100996,69972,2019-12-26,Salvador Shopping,Sapato Estampa,5,358,1790,<bound method Series.mean of 1 18.00\n2 ...,Mateus